version: "3.9"

services:
  db:
    image: postgres:16
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  backend:
    build: ./Backend
    volumes:
      - ./Backend:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  frontend:
    build: ./Frontend
    ports:
      - "4200:4200"
    depends_on:
      - backend

volumes:
  postgres_data:
